### ISSUE TITLE
Tracker errors

### ISSUE THREAD

**Issue by 119z** [null2264/yokai#46]
### Steps to reproduce

1. Open manga
2. Attempt to track it. If already being tracked, read a chapter or try to manually change the chapter number in tracker.
3. Error shows up

### Expected behavior

No error to pop up

### Actual behavior

I was reading manga as usual, and I noticed that some errors pop up when I read a chapter or if I tried to search for the manga. I only tested MangaUpdates, Anlist and MyAnimeList since those are the three trackers I have.

[Here's the error that appears on Yokai](https://ibb.co/album/fkzLyC) vs it [working as normal on Mihon
](https://ibb.co/album/Dzz81v)

### Yōkai version

1.7.14

### Android version

13

### Device

OPPO Reno 5 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It looks like a connection issue. Can you try again using different connection or using a VPN?

**Comment by 119z** [comment]
Seems to be working when I use a VPN. Weird because it'd been working normally previously, but no big deal. Thanks for the help!
